config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"

  resources :questions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 3}

  def formatted_created_at
    self.created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @name = params[:name]
  end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end
  
  def create
    @question = Question.new question_params
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    @question = Question.find_by id: params[:id]
  end

  def update
    @question = Question.find_by id: params[:id]
    if @question.update question_params
      redirect_to questions_path
    else
      render :edit
    end
  end
  
  def destroy
    @question = Question.find_by id: params[:id]
    @question.destroy
    redirect_to questions_path
  end
  
  
  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AskIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Questions', questions_path %></li>
        <li><%= link_to 'New Question', new_question_path %></li>
      </ul>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages</h1>
<h3>Добрый день, <%= @name %></h3>
&copy; @Dubovtsov <%= Time.now.year %>

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, required: true, minlength: 2, placeholder: "Title" %>
    
    <%= f.label :body %>
    <%= f.text_area :body, required: true, minlength: 2, placeholder: "Body" %>

    <%= f.submit "Обновить" %>
  </div>
 
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<h1>Questions</h1>
<h3>Добрый день, <%= @name %></h3>

  <% @questions.each do |question| %>

  <h1>
    <%= question.title %>
  </h1>

  <time datetime="<%= question.formatted_created_at %>"><%= question.formatted_created_at %></time>

  <p>
    <%= question.body %>
  </p>

  <%= link_to 'Edit', edit_question_path(question) %> | 
  <%= link_to 'Destroy', question_path(question), method: :delete %>
  <%= button_to "Delete", question_path(question), method: :delete %>
  <hr>

  <% end %>

&copy; @Dubovtsov <%= Time.now.year %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>